# Generated by Django 5.0.7 on 2024-12-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_author_article_no_author_date_author_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
